inputs=[
    #"take tablet",
    #"use tablet",
    "go doorway",
    "go north",
    "go north",
    "go bridge",
    "go continue",
    "go down",
    "go east",
    "take empty lantern",
    "go west",
    "go west",
    "go passage",
    "go ladder",
    "go west",
    "go south",
    "go north",
    "take can",
    "use can",
    "use lantern",
    "go west",
    "go ladder",
    "go darkness",
    "go continue",
    "go west",
    "go west",
    "go west",
    "go west",
    "go north",
    "take red coin",
    "go north",
    ["go west",
     "take blue coin",
     "go up",
     "take shiny coin",
     "go down",
     "go east"],
    ["go east",
     "take concave coin",
     "go down",
     "take corroded coin,
     "go up",
     "go west"],
    "use blue coin",
    "use red coin",
    "use shiny coin",
    "use concave coin",
    "use corroded coin",
    "go north",
    "use teleporter
]

coinPuzzle=[
    "red coin-2 dots",
    "blue coin-9 dots",
    "shiny coin-pentagon",
    "concave coin-7 sides",
    "corroded coin-triangle",
    "puzzle-   _ + _ * _^2 + _^3 - _ = 399",
    "solution- 9   2   5     7     3",
    "names-blue red shiny concave corroded
]

codes=[
    "one on the site upon signing up?",
    "one in arch_spec",
    "one easily read in the bin file",
    "one after passing the self-test",
    "one after using the tablet",
    "one writte in the maze wall",
    "one after solving the coin puzzle"
]
